[workspace]
authors = ["DanielBoigk <dn.boigk@gmail.com>"]
channels = ["conda-forge"]
name = "obsidian_prompts"
platforms = ["linux-64"]
version = "0.1.0"


[dependencies]
python = "*"
deno = "*"

[pypi-dependencies]
cocoindex = "*"
kuzu = "*"

