[workspace]
authors = ["DanielBoigk <dn.boigk@gmail.com>"]
channels = ["conda-forge"]
name = "obsidian_prompts"
platforms = ["linux-64"]
version = "0.1.0"


[dependencies]
python = "*"
deno = "*"
pypdf = ">=6.1.1,<7"
python-dotenv = ">=1.1.1,<2"

[pypi-dependencies]
cocoindex = { version = "*", extras = ["embeddings"] }
kuzu = "*"
marker-pdf = "*"

